### ISSUE TITLE
Please can we have GPU driver configuration that supports Mediatek Helio G processors right now in this decent age.

### ISSUE THREAD

**Issue by Mountain558** [Ishan0981/Skyline-Enhanced-Infinity#1]
Can we please have GPU driver configuration that supports with custom drivers for Mediatek Helio G processors that work on this Skyline enhanced infinity emulator please since I have Mediatek Helio G96 processor on my Xiaomi redmi note 11 pro 4G smartphone. However, sadly I can't play Nintendo Switch game roms like MK1 remake video game in this emulator, it is really sad to see this coming for this emulator dammit.

**Comment by Mountain558** [comment]
![IMG_20230923_134942](https://github.com/Ishan0981/Skyline-Enhanced-Infinity/assets/113456314/44b09862-27da-444f-9744-b7f9e8d9d536)

**Comment by Ishan0981** [comment]
This Is Not Possible To Use GPU Driver In Mali Device.
