### ISSUE TITLE
Emulator crash alot when entering the game & while playing the game

### ISSUE THREAD

**Issue by YuenEye** [Ishan0981/Skyline-Enhanced-Infinity#2]
Tested on;

Device: Tecno Pova 5 pro 5g
Processor: Dimensity 6080
8gb Ram
256 Rom
GPU: Mali G57

No problem about the fps,  just the crash issue.

Game tested on;

Pokémon Sword
Pokémon Shield
Pokémon Legend of Arceus

**Comment by Ishan0981** [comment]
This Is Not Emulator Problem.This Is Coming From Google August Security Patch Update.
Solution - Use Save File of Pokemon Let's Go Pikachu, You Can Get From Our Discord Server And This Save File Is From Starting So Don't Worry.
